<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Anggotakk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Anggotakk_model');
    } 

    /*
     * Listing of anggotakk
     */
    function index()
    {
        $data['anggotakk'] = $this->Anggotakk_model->get_all_anggotakk();
        
        redirect('Kk');
    }

   

    /*
     * Adding a new anggotakk
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Kawin','Kawin','required');
		$this->form_validation->set_rules('Nama','Nama','required|max_length[50]');
		$this->form_validation->set_rules('JenisKel','JenisKel','required');
		$this->form_validation->set_rules('Tl','Tl','required|max_length[50]');
		$this->form_validation->set_rules('Tgl','Tgl','required');
		$this->form_validation->set_rules('Agama','Agama','required|max_length[50]');
		$this->form_validation->set_rules('Pendidikan','Pendidikan','required|max_length[50]');
		$this->form_validation->set_rules('JenisPek','JenisPek','required|max_length[50]');
		$this->form_validation->set_rules('Hubkel','Hubkel','required|max_length[50]');
		$this->form_validation->set_rules('Kewarganegaraan','Kewarganegaraan','required|max_length[50]');
		$this->form_validation->set_rules('Ayah','Ayah','required|max_length[50]');
		$this->form_validation->set_rules('Ibu','Ibu','required|max_length[50]');
		$this->form_validation->set_rules('Nokk','Nokk','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'Kawin' => $this->input->post('Kawin'),
				'JenisKel' => $this->input->post('JenisKel'),
				'Agama' => $this->input->post('Agama'),
				'Kewarganegaraan' => $this->input->post('Kewarganegaraan'),
				'Nama' => $this->input->post('Nama'),
				'Tl' => $this->input->post('Tl'),
				'Tgl' => $this->input->post('Tgl'),
				'Pendidikan' => $this->input->post('Pendidikan'),
				'JenisPek' => $this->input->post('JenisPek'),
				'Hubkel' => $this->input->post('Hubkel'),
				'Nopaspor' => $this->input->post('Nopaspor'),
				'Nokitap' => $this->input->post('Nokitap'),
				'Ayah' => $this->input->post('Ayah'),
				'Ibu' => $this->input->post('Ibu'),
				'Nokk' => $this->input->post('Nokk'),
            );
            
            $anggotakk_id = $this->Anggotakk_model->add_anggotakk($params);
            redirect('anggotakk/index');
        }
        else
        {            
            $data['_view'] = 'anggotakk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a anggotakk
     */
    function edit($Nik)
    {   
        // check if the anggotakk exists before trying to edit it
        $data['anggotakk'] = $this->Anggotakk_model->get_anggotakk2($Nik);
        
        if(isset($data['anggotakk']['Nik']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Kawin','Kawin','required');
			$this->form_validation->set_rules('Nama','Nama','required|max_length[50]');
			$this->form_validation->set_rules('JenisKel','JenisKel','required');
			$this->form_validation->set_rules('Tl','Tl','required|max_length[50]');
			$this->form_validation->set_rules('Tgl','Tgl','required');
			$this->form_validation->set_rules('Agama','Agama','required|max_length[50]');
			$this->form_validation->set_rules('Pendidikan','Pendidikan','required|max_length[50]');
			$this->form_validation->set_rules('JenisPek','JenisPek','required|max_length[50]');
			$this->form_validation->set_rules('Hubkel','Hubkel','required|max_length[50]');
			$this->form_validation->set_rules('Kewarganegaraan','Kewarganegaraan','required|max_length[50]');
			$this->form_validation->set_rules('Ayah','Ayah','required|max_length[50]');
			$this->form_validation->set_rules('Ibu','Ibu','required|max_length[50]');
            // $this->form_validation->set_rules('Nokk','Nokk','required');
            
            $params = array(
                'Kawin' => $this->input->post('Kawin'),
                'JenisKel' => $this->input->post('JenisKel'),
                'Agama' => $this->input->post('Agama'),
                'Kewarganegaraan' => $this->input->post('Kewarganegaraan'),
                'Nama' => $this->input->post('Nama'),
                'Tl' => $this->input->post('Tl'),
                'Tgl' => $this->input->post('Tgl'),
                'Pendidikan' => $this->input->post('Pendidikan'),
                'JenisPek' => $this->input->post('JenisPek'),
                'Hubkel' => $this->input->post('Hubkel'),
                'Nopaspor' => $this->input->post('Nopaspor'),
                'Nokitap' => $this->input->post('Nokitap'),
                'Ayah' => $this->input->post('Ayah'),
                'Ibu' => $this->input->post('Ibu'),
                // 'Nokk' => $this->input->post('Nokk'),
            );

            foreach ($params as $item){
                echo $item;
            }
			if($this->form_validation->run())     
            {   
                $params = array(
					'Kawin' => $this->input->post('Kawin'),
					'JenisKel' => $this->input->post('JenisKel'),
					'Agama' => $this->input->post('Agama'),
					'Kewarganegaraan' => $this->input->post('Kewarganegaraan'),
					'Nama' => $this->input->post('Nama'),
					'Tl' => $this->input->post('Tl'),
					'Tgl' => $this->input->post('Tgl'),
					'Pendidikan' => $this->input->post('Pendidikan'),
					'JenisPek' => $this->input->post('JenisPek'),
					'Hubkel' => $this->input->post('Hubkel'),
					'Nopaspor' => $this->input->post('Nopaspor'),
					'Nokitap' => $this->input->post('Nokitap'),
					'Ayah' => $this->input->post('Ayah'),
					'Ibu' => $this->input->post('Ibu'),
					// 'Nokk' => $this->input->post('Nokk'),
                );

                $this->Anggotakk_model->update_anggotakk($Nik,$params);            
                redirect('Kk');
            }
            else
            {
                $data['_view'] = 'anggotakk/edit';
                $this->load->view($data['_view'],$data);
            }
        }
        else
            show_error('The anggotakk you are trying to edit does not exist.');
    } 

    /*
     * Deleting anggotakk
     */
    function remove($Nik)
    {
        $anggotakk = $this->Anggotakk_model->get_anggotakk($Nik);

        // check if the anggotakk exists before trying to delete it
        if(isset($anggotakk['Nik']))
        {
            $this->Anggotakk_model->delete_anggotakk($Nik);
            redirect('anggotakk/index');
        }
        else
            show_error('The anggotakk you are trying to delete does not exist.');
    }
    
}
