<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kk_model');
        $this->load->model('Anggotakk_model');
        // $this->load->library('m_pdf');
    } 

    /*
     * Listing of kk
     */
    function index()
    {
        if(isset($this->session->userdata['Nokk'])){
            $data['kk'] = $this->Kk_model->get_kk($this->session->userdata['Nokk']);
            $data['anggota']= $this->Anggotakk_model->get_anggotakk($this->session->userdata['Nokk']);
            $data['_view'] = 'kk/index';
            $this->load->view($data['_view'],$data);
        }
       else{
        redirect('Welcome');
       } 
    }

    function cetak(){
        $data['_view'] = 'kk/print';
        $data['kk'] = $this->Kk_model->get_kk($this->session->userdata['Nokk']);
        $data['anggotakk']= $this->Anggotakk_model->get_anggotakk2($this->input->post('Nik'));
        // $this->load->library('pdfgenerator');
        $this->load->view($data['_view'],$data);
        // $this->pdfgenerator->generate($html,'print');
    }

    /*
     * Adding a new kk
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Alamat','Alamat','required|max_length[50]');
		$this->form_validation->set_rules('RT/RW','RT/RW','required|max_length[20]');
		$this->form_validation->set_rules('Kodepos','Kodepos','required|integer');
		$this->form_validation->set_rules('Desakel','Desakel','required|max_length[50]');
		$this->form_validation->set_rules('Kecamatan','Kecamatan','required|max_length[50]');
		$this->form_validation->set_rules('Kabkota','Kabkota','required|max_length[50]');
		$this->form_validation->set_rules('Provinsi','Provinsi','required|max_length[50]');
		$this->form_validation->set_rules('kk','Kk','required|max_length[50]');
		$this->form_validation->set_rules('Kepkeluarga','Kepkeluarga','required|max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'Alamat' => $this->input->post('Alamat'),
				'RT/RW' => $this->input->post('RT/RW'),
				'Kodepos' => $this->input->post('Kodepos'),
				'Desakel' => $this->input->post('Desakel'),
				'Kecamatan' => $this->input->post('Kecamatan'),
				'Kabkota' => $this->input->post('Kabkota'),
				'Provinsi' => $this->input->post('Provinsi'),
				'kk' => $this->input->post('kk'),
				'Kepkeluarga' => $this->input->post('Kepkeluarga'),
            );
            
            $kk_id = $this->Kk_model->add_kk($params);
            redirect('kk/index');
        }
        else
        {            
            $data['_view'] = 'kk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kk
     */
    function edit($Nokk)
    {   
        // check if the kk exists before trying to edit it
        $data['kk'] = $this->Kk_model->get_kk($Nokk);
        
        if(isset($data['kk']['Nokk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Alamat','Alamat','required|max_length[50]');
			$this->form_validation->set_rules('RT/RW','RT/RW','required|max_length[20]');
			$this->form_validation->set_rules('Kodepos','Kodepos','required|integer');
			$this->form_validation->set_rules('Desakel','Desakel','required|max_length[50]');
			$this->form_validation->set_rules('Kecamatan','Kecamatan','required|max_length[50]');
			$this->form_validation->set_rules('Kabkota','Kabkota','required|max_length[50]');
			$this->form_validation->set_rules('Provinsi','Provinsi','required|max_length[50]');
			$this->form_validation->set_rules('kk','Kk','required|max_length[50]');
			$this->form_validation->set_rules('Kepkeluarga','Kepkeluarga','required|max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'Alamat' => $this->input->post('Alamat'),
					'RT/RW' => $this->input->post('RT/RW'),
					'Kodepos' => $this->input->post('Kodepos'),
					'Desakel' => $this->input->post('Desakel'),
					'Kecamatan' => $this->input->post('Kecamatan'),
					'Kabkota' => $this->input->post('Kabkota'),
					'Provinsi' => $this->input->post('Provinsi'),
					'kk' => $this->input->post('kk'),
					'Kepkeluarga' => $this->input->post('Kepkeluarga'),
                );

                $this->Kk_model->update_kk($Nokk,$params);            
                redirect('kk/index');
            }
            else
            {
                $data['_view'] = 'kk/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kk you are trying to edit does not exist.');
    } 

    /*
     * Deleting kk
     */
    function remove($Nokk)
    {
        $kk = $this->Kk_model->get_kk($Nokk);

        // check if the kk exists before trying to delete it
        if(isset($kk['Nokk']))
        {
            $this->Kk_model->delete_kk($Nokk);
            redirect('kk/index');
        }
        else
            show_error('The kk you are trying to delete does not exist.');
    }
    
}
