<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Anggotakk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get anggotakk by Nik
     */
    function get_anggotakk($Nokk)
    {
        return $this->db->get_where('anggotakk',array('Nokk'=>$Nokk))->result_array();
    }

    function get_anggotakk2($Nik)
    {
        return $this->db->get_where('anggotakk',array('Nik'=>$Nik))->row_array();
    }
        
    /*
     * Get all anggotakk
     */
    function get_all_anggotakk()
    {
        $this->db->order_by('Nik', 'desc');
        return $this->db->get('anggotakk')->result_array();
    }
        
    /*
     * function to add new anggotakk
     */
    function add_anggotakk($params)
    {
        $this->db->insert('anggotakk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update anggotakk
     */
    function update_anggotakk($Nik,$params)
    {
        $this->db->where('Nik',$Nik);
        return $this->db->update('anggotakk',$params);
    }
    
    /*
     * function to delete anggotakk
     */
    function delete_anggotakk($Nik)
    {
        return $this->db->delete('anggotakk',array('Nik'=>$Nik));
    }
}
