<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kk by Nokk
     */
    function get_kk($Nokk)
    {
        return $this->db->get_where('kk',array('Nokk'=>$Nokk))->result_array();
    }
        
    /*
     * Get all kk
     */
    function get_all_kk()
    {
        $this->db->order_by('Nokk', 'desc');
        return $this->db->get('kk')->result_array();
    }
        
    /*
     * function to add new kk
     */
    function add_kk($params)
    {
        $this->db->insert('kk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kk
     */
    function update_kk($Nokk,$params)
    {
        $this->db->where('Nokk',$Nokk);
        return $this->db->update('kk',$params);
    }
    
    /*
     * function to delete kk
     */
    function delete_kk($Nokk)
    {
        return $this->db->delete('kk',array('Nokk'=>$Nokk));
    }
}
